Insert into state (abbreviation, "name") values ('AA', 'Armed Forces (the) Americas');
Insert into state (abbreviation, "name") values ('AB', 'Alberta');
Insert into state (abbreviation, "name") values ('AE', 'Armed Forces Europe');
Insert into state (abbreviation, "name") values ('AK', 'Alaska');
Insert into state (abbreviation, "name") values ('AL', 'Alabama');
Insert into state (abbreviation, "name") values ('AP', 'Armed Forces Pacific');
Insert into state (abbreviation, "name") values ('AR', 'Arkansas');
Insert into state (abbreviation, "name") values ('AS', 'American Samoa');
Insert into state (abbreviation, "name") values ('AZ', 'Arizona');
Insert into state (abbreviation, "name") values ('BC', 'British Columbia');
Insert into state (abbreviation, "name") values ('CA', 'California');
Insert into state (abbreviation, "name") values ('CD', 'Canada');
Insert into state (abbreviation, "name") values ('CO', 'Colorado');
Insert into state (abbreviation, "name") values ('CT', 'Connecticut');
Insert into state (abbreviation, "name") values ('DC', 'Dist. Of Columbia');
Insert into state (abbreviation, "name") values ('DE', 'Delaware');
Insert into state (abbreviation, "name") values ('FF', 'Foreign Countries');
Insert into state (abbreviation, "name") values ('FL', 'Florida');
Insert into state (abbreviation, "name") values ('GA', 'Georgia');
Insert into state (abbreviation, "name") values ('GU', 'Guam');
Insert into state (abbreviation, "name") values ('HI', 'Hawaii');
Insert into state (abbreviation, "name") values ('IA', 'Iowa');
Insert into state (abbreviation, "name") values ('ID', 'Idaho');
Insert into state (abbreviation, "name") values ('IL', 'Illinois');
Insert into state (abbreviation, "name") values ('IN', 'Indiana');
Insert into state (abbreviation, "name") values ('KS', 'Kansas');
Insert into state (abbreviation, "name") values ('KY', 'Kentucky');
Insert into state (abbreviation, "name") values ('LA', 'Louisiana');
Insert into state (abbreviation, "name") values ('MA', 'Massachusetts');
Insert into state (abbreviation, "name") values ('MB', 'Manitoba');
Insert into state (abbreviation, "name") values ('MD', 'Maryland');
Insert into state (abbreviation, "name") values ('ME', 'Maine');
Insert into state (abbreviation, "name") values ('MI', 'Michigan');
Insert into state (abbreviation, "name") values ('MN', 'Minnesota');
Insert into state (abbreviation, "name") values ('MO', 'Missouri');
Insert into state (abbreviation, "name") values ('MS', 'Mississippi');
Insert into state (abbreviation, "name") values ('MT', 'Montana');
Insert into state (abbreviation, "name") values ('MX', 'Mexico');
Insert into state (abbreviation, "name") values ('NB', 'New Brunswick');
Insert into state (abbreviation, "name") values ('NC', 'North Carolina');
Insert into state (abbreviation, "name") values ('ND', 'North Dakota');
Insert into state (abbreviation, "name") values ('NE', 'Nebraska');
Insert into state (abbreviation, "name") values ('NH', 'New Hampshire');
Insert into state (abbreviation, "name") values ('NJ', 'New Jersey');
Insert into state (abbreviation, "name") values ('NL', 'Newfoundland and Labrador');
Insert into state (abbreviation, "name") values ('NM', 'New Mexico');
Insert into state (abbreviation, "name") values ('NS', 'Nova Scotia');
Insert into state (abbreviation, "name") values ('NT', 'Northwest Territories');
Insert into state (abbreviation, "name") values ('NU', 'Nunavut');
Insert into state (abbreviation, "name") values ('NV', 'Nevada');
Insert into state (abbreviation, "name") values ('NY', 'New York');
Insert into state (abbreviation, "name") values ('OH', 'Ohio');
Insert into state (abbreviation, "name") values ('OK', 'Oklahoma');
Insert into state (abbreviation, "name") values ('ON', 'Ontario');
Insert into state (abbreviation, "name") values ('OR', 'Oregon');
Insert into state (abbreviation, "name") values ('PA', 'Pennsylvania');
Insert into state (abbreviation, "name") values ('PE', 'Prince Edward Island');
Insert into state (abbreviation, "name") values ('PR', 'Puerto Rico');
Insert into state (abbreviation, "name") values ('QC', 'Quebec');
Insert into state (abbreviation, "name") values ('RI', 'Rhode Island');
Insert into state (abbreviation, "name") values ('SC', 'South Carolina');
Insert into state (abbreviation, "name") values ('SD', 'South Dakota');
Insert into state (abbreviation, "name") values ('SK', 'Saskatchewan');
Insert into state (abbreviation, "name") values ('TN', 'Tennessee');
Insert into state (abbreviation, "name") values ('TT', 'Trust Territory');
Insert into state (abbreviation, "name") values ('TX', 'Texas');
Insert into state (abbreviation, "name") values ('UN', 'Unknown');
Insert into state (abbreviation, "name") values ('UT', 'Utah');
Insert into state (abbreviation, "name") values ('VA', 'Virginia');
Insert into state (abbreviation, "name") values ('VI', 'Virgin Islands');
Insert into state (abbreviation, "name") values ('VT', 'Vermont');
Insert into state (abbreviation, "name") values ('WA', 'Washington');
Insert into state (abbreviation, "name") values ('WI', 'Wisconsin');
Insert into state (abbreviation, "name") values ('WV', 'West Virginia');
Insert into state (abbreviation, "name") values ('WY', 'Wyoming');
Insert into state (abbreviation, "name") values ('YT', 'Yukon ');
